version: '3.8'

services:
  jarvais-api:
    build: .
    ports:
      - "5000:5000"
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_DB=0
    #   - SESSION_TTL=3600
    # depends_on:
    #   - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: ["python", "src/app.py"]

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: