[project]
authors = ["skim2257 <Sejin Kim>"]
channels = ["conda-forge"]
description = "Microservice to return jarvAIs Analyzer results compatible with HighCharts using FastAPI"
name = "jarvais-highcharts-service"
platforms = ["osx-64", "linux-64", "win-64", "linux-aarch64"]
version = "1.2.0"

[tasks]
dev = "RELOAD=true LOG_LEVEL=debug python run_fastapi.py"
prod = "PRODUCTION=true APP_FILE=main python run_fastapi.py"
test-server = "python run_fastapi.py"
test = "python tests/test_fastapi.py"
docs = "echo 'API docs available at http://localhost:8888/docs'"

[activation.env]
HOST="0.0.0.0"
PORT="8888"
REDIS_HOST="redis"
REDIS_PORT="6379"

[dependencies]
python = "3.12.*"
redis-py = ">=5.0.1,<6"
requests = ">=2.31.0,<3"

[pypi-dependencies]
fastapi = ">=0.104.1,<0.105"
uvicorn = { version = ">=0.24.0,<0.25", extras = ["standard"] }
python-multipart = ">=0.0.6,<0.1"
pydantic = ">=2.5.0,<3"
slowapi = ">=0.1.9,<0.2"
umap-learn = ">=0.5.5,<0.6"
typing_extensions = ">=4.14.1,<5"
jarvais = ">=0.20.0, <0.21"




