[project]
authors = ["skim2257 <Sejin Kim>"]
channels = ["conda-forge"]
description = "Microservice to return jarvAIs Analyzer results compatible with HighCharts"
name = "jarvais-highcharts-service"
platforms = ["osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
jarvais = ">=0.13.1, <0.14"

